CREATE DATABASE IF NOT EXISTS crm_db;
USE crm_db;
CREATE TABLE contacts (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), email VARCHAR(100), phone VARCHAR(20), company VARCHAR(100));
CREATE TABLE accounts (id INT AUTO_INCREMENT PRIMARY KEY, company_name VARCHAR(100), industry VARCHAR(100), revenue FLOAT);
CREATE TABLE sales (id INT AUTO_INCREMENT PRIMARY KEY, lead_name VARCHAR(100), deal_value FLOAT, status VARCHAR(50));
CREATE TABLE marketing (id INT AUTO_INCREMENT PRIMARY KEY, campaign_name VARCHAR(100), channel VARCHAR(50), start_date DATE);
CREATE TABLE support (id INT AUTO_INCREMENT PRIMARY KEY, customer_name VARCHAR(100), issue TEXT);
CREATE TABLE analytics (id INT AUTO_INCREMENT PRIMARY KEY, metric_name VARCHAR(100), value VARCHAR(100));